DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '1');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '2');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '3');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '4');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '5');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '6');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '7');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '8');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '9');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '10');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '11');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '12');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '13');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '14');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '15');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '16');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '17');
DELETE FROM `war_world`.`rvr_progression` WHERE (`BattleFrontId` = '18');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Chaos Wastes', '1', '15', '2', '11', '103', '2', '0', '2', '0', '0', '0', '19', '20');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Praag', '2', '1', '3', '11', '105', '0', '1', '0', '1', '0', '0', '18', '17');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Reikland', '3', '2', '13', '11', '109', '1', '0', '1', '0', '0', '0', '15', '16');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Black Crag', '4', '16', '5', '2', '3', '2', '0', '2', '0', '0', '0', '10', '9');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Thunder Mountain', '5', '4', '6', '2', '5', '0', '0', '0', '0', '0', '0', '7', '8');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Kadrin Valley', '6', '5', '14', '2', '9', '1', '0', '1', '0', '0', '0', '6', '5');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Eataine', '7', '8', '17', '4', '209', '1', '0', '1', '0', '0', '0', '26', '25');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Dragonwake', '8', '9', '7', '4', '205', '0', '0', '0', '0', '0', '0', '28', '27');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Caledor', '9', '18', '8', '4', '203', '2', '0', '2', '0', '0', '0', '29', '30');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('1', '2', 'Norsca / Nordland', '10', '11', '11', '8', '106', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('1', '1', 'Ekrund / Mt Bloodhorn', '11', '12', '12', '1', '6', '2', '0', '2', '1', '0', '0', '0', '0');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('1', '3', 'Chrace / Blighted Isle', '12', '10', '10', '3', '206', '1', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'Reikwald', '13', '2', '2', '11', '110', '1', '0', '1', '0', '0', '0', '100', '100');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Stonewatch', '14', '2', '2', '2', '10', '1', '0', '1', '0', '0', '0', '14', '14');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '2', 'The Maw', '15', '5', '5', '11', '104', '2', '0', '2', '0', '0', '0', '101', '101');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '1', 'Butchers Pass', '16', '2', '2', '2', '4', '2', '0', '2', '0', '0', '0', '102', '102');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Shining Way', '17', '2', '2', '4', '210', '2', '0', '2', '0', '0', '0', '105', '105');
INSERT INTO `war_world`.`rvr_progression` (`tier`, `PairingId`, `Description`, `BattleFrontId`, `OrderWinProgression`, `DestWinProgression`, `RegionId`, `ZoneId`, `DefaultRealmLock`, `ResetProgressionOnEntry`, `LastOwningRealm`, `LastOpenedZone`, `OrderVP`, `DestroVP`, `DestroKeepId`, `OrderKeepId`) VALUES ('4', '3', 'Fell Landing', '18', '2', '2', '4', '204', '2', '0', '2', '0', '0', '0', '104', '104');


UPDATE `war_world`.`rvr_progression` SET `OrderWinProgression` = '5', `DestWinProgression` = '5' WHERE (`BattleFrontId` = '13');
UPDATE `war_world`.`rvr_progression` SET `OrderWinProgression` = '8', `DestWinProgression` = '8' WHERE (`BattleFrontId` = '14');
UPDATE `war_world`.`rvr_progression` SET `OrderWinProgression` = '8', `DestWinProgression` = '8' WHERE (`BattleFrontId` = '16');

UPDATE `war_world`.`rvr_progression` SET `DestroKeepId` = '103', `OrderKeepId` = '103' WHERE (`BattleFrontId` = '14');


DELETE FROM `war_world`.`keep_infos` WHERE (`KeepId` = '100');
DELETE FROM `war_world`.`keep_infos` WHERE (`KeepId` = '101');
DELETE FROM `war_world`.`keep_infos` WHERE (`KeepId` = '102');
DELETE FROM `war_world`.`keep_infos` WHERE (`KeepId` = '103');
DELETE FROM `war_world`.`keep_infos` WHERE (`KeepId` = '104');
DELETE FROM `war_world`.`keep_infos` WHERE (`KeepId` = '105');
INSERT INTO `war_world`.`keep_infos` (`KeepId`, `Name`, `Realm`, `DoorCount`, `ZoneId`, `RegionId`, `X`, `Y`, `Z`, `O`, `PQuestId`, `Race`, `OilX`, `OilY`, `OilZ`, `OilO`, `OilOuterX`, `OilOuterY`, `OilOuterZ`, `OilOuterO`, `RamX`, `RamY`, `RamZ`, `RamO`, `RamOuterX`, `RamOuterY`, `RamOuterZ`, `RamOuterO`, `IsFortress`, `OilOuter1X`, `OilOuter1Y`, `OilOuter1Z`, `OilOuter1O`, `OilOuter2X`, `OilOuter2Y`, `OilOuter2Z`, `OilOuter2O`, `RamOuter1X`, `RamOuter1Y`, `RamOuter1Z`, `RamOuter1O`, `RamOuter2X`, `RamOuter2Y`, `RamOuter2Z`, `RamOuter2O`) VALUES ('100', 'Reikwald', '1', '4', '110', '11', '1431158', '966414', '15955', '2042', '9999', '3', '1431156', '965739', '16455', '2026', '1431197', '961314', '16790', '2030', '1431157', '965556', '15904', '78', '1431205', '961235', '15952', '52', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`keep_infos` (`KeepId`, `Name`, `Realm`, `DoorCount`, `ZoneId`, `RegionId`, `X`, `Y`, `Z`, `O`, `PQuestId`, `Race`, `OilX`, `OilY`, `OilZ`, `OilO`, `OilOuterX`, `OilOuterY`, `OilOuterZ`, `OilOuterO`, `RamX`, `RamY`, `RamZ`, `RamO`, `RamOuterX`, `RamOuterY`, `RamOuterZ`, `RamOuterO`, `IsFortress`, `OilOuter1X`, `OilOuter1Y`, `OilOuter1Z`, `OilOuter1O`, `OilOuter2X`, `OilOuter2Y`, `OilOuter2Z`, `OilOuter2O`, `RamOuter1X`, `RamOuter1Y`, `RamOuter1Z`, `RamOuter1O`, `RamOuter2X`, `RamOuter2Y`, `RamOuter2Z`, `RamOuter2O`) VALUES ('101', 'The Maw', '2', '4', '104', '11', '1429597', '740733', '14518', '2', '9998', '4', '1429595', '741865', '15018', '14', '1429554', '747051', '14181', '58', '1429586', '741962', '14488', '2108', '1429552', '747063', '13371', '2040', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`keep_infos` (`KeepId`, `Name`, `Realm`, `DoorCount`, `ZoneId`, `RegionId`, `X`, `Y`, `Z`, `O`, `PQuestId`, `Race`, `OilX`, `OilY`, `OilZ`, `OilO`, `OilOuterX`, `OilOuterY`, `OilOuterZ`, `OilOuterO`, `RamX`, `RamY`, `RamZ`, `RamO`, `RamOuterX`, `RamOuterY`, `RamOuterZ`, `RamOuterO`, `IsFortress`, `OilOuter1X`, `OilOuter1Y`, `OilOuter1Z`, `OilOuter1O`, `OilOuter2X`, `OilOuter2Y`, `OilOuter2Z`, `OilOuter2O`, `RamOuter1X`, `RamOuter1Y`, `RamOuter1Z`, `RamOuter1O`, `RamOuter2X`, `RamOuter2Y`, `RamOuter2Z`, `RamOuter2O`) VALUES ('102', 'Butcher\'s pass', '2', '4', '4', '2', '1398796', '1040120', '8847', '2068', '0', '2', '1398846', '1038904', '9566', '2082', '1399056', '1034587', '9068', '2110', '1398854', '1038904', '8903', '42', '1399062', '1034508', '8264', '24', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`keep_infos` (`KeepId`, `Name`, `Realm`, `DoorCount`, `ZoneId`, `RegionId`, `X`, `Y`, `Z`, `O`, `PQuestId`, `Race`, `OilX`, `OilY`, `OilZ`, `OilO`, `OilOuterX`, `OilOuterY`, `OilOuterZ`, `OilOuterO`, `RamX`, `RamY`, `RamZ`, `RamO`, `RamOuterX`, `RamOuterY`, `RamOuterZ`, `RamOuterO`, `IsFortress`, `OilOuter1X`, `OilOuter1Y`, `OilOuter1Z`, `OilOuter1O`, `OilOuter2X`, `OilOuter2Y`, `OilOuter2Z`, `OilOuter2O`, `RamOuter1X`, `RamOuter1Y`, `RamOuter1Z`, `RamOuter1O`, `RamOuter2X`, `RamOuter2Y`, `RamOuter2Z`, `RamOuter2O`) VALUES ('103', 'Stonewatch', '2', '4', '10', '2', '1398796', '1040120', '8847', '2068', '0', '2', '1398846', '1038904', '9566', '2082', '1399056', '1034587', '9068', '2110', '1398854', '1038904', '8903', '42', '1399062', '1034508', '8264', '24', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`keep_infos` (`KeepId`, `Name`, `Realm`, `DoorCount`, `ZoneId`, `RegionId`, `X`, `Y`, `Z`, `O`, `PQuestId`, `Race`, `OilX`, `OilY`, `OilZ`, `OilO`, `OilOuterX`, `OilOuterY`, `OilOuterZ`, `OilOuterO`, `RamX`, `RamY`, `RamZ`, `RamO`, `RamOuterX`, `RamOuterY`, `RamOuterZ`, `RamOuterO`, `IsFortress`, `OilOuter1X`, `OilOuter1Y`, `OilOuter1Z`, `OilOuter1O`, `OilOuter2X`, `OilOuter2Y`, `OilOuter2Z`, `OilOuter2O`, `RamOuter1X`, `RamOuter1Y`, `RamOuter1Z`, `RamOuter1O`, `RamOuter2X`, `RamOuter2Y`, `RamOuter2Z`, `RamOuter2O`) VALUES ('104', 'Fell Landing', '2', '4', '204', '4', '1398796', '1040120', '8847', '2068', '0', '2', '1398846', '1038904', '9566', '2082', '1399056', '1034587', '9068', '2110', '1398854', '1038904', '8903', '42', '1399062', '1034508', '8264', '24', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `war_world`.`keep_infos` (`KeepId`, `Name`, `Realm`, `DoorCount`, `ZoneId`, `RegionId`, `X`, `Y`, `Z`, `O`, `PQuestId`, `Race`, `OilX`, `OilY`, `OilZ`, `OilO`, `OilOuterX`, `OilOuterY`, `OilOuterZ`, `OilOuterO`, `RamX`, `RamY`, `RamZ`, `RamO`, `RamOuterX`, `RamOuterY`, `RamOuterZ`, `RamOuterO`, `IsFortress`, `OilOuter1X`, `OilOuter1Y`, `OilOuter1Z`, `OilOuter1O`, `OilOuter2X`, `OilOuter2Y`, `OilOuter2Z`, `OilOuter2O`, `RamOuter1X`, `RamOuter1Y`, `RamOuter1Z`, `RamOuter1O`, `RamOuter2X`, `RamOuter2Y`, `RamOuter2Z`, `RamOuter2O`) VALUES ('105', 'Shining Way', '2', '4', '210', '4', '1398796', '1040120', '8847', '2068', '9996', '2', '1398846', '1038904', '9566', '2082', '1399056', '1034587', '9068', '2110', '1398854', '1038904', '8903', '42', '1399062', '1034508', '8264', '24', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
