-- WAR_V_1_0_53.sql
-- WAR Aegis Change
UPDATE `war_world`.`buff_infos` SET `Silent` = '0' WHERE (`Entry` = '15147');
UPDATE `war_world`.`item_infos` SET `Name` = 'WAR Aegis', `SellPrice` = '175', `ObjectLevel` = '10' WHERE (`Entry` = '207814');
UPDATE `war_world`.`buff_commands` SET `SecondaryValue` = '20' WHERE (`Entry` = '15147') and (`CommandID` = '0') and (`CommandSequence` = '0');
UPDATE `war_world`.`buff_commands` SET `SecondaryValue` = '20' WHERE (`Entry` = '15147') and (`CommandID` = '0') and (`CommandSequence` = '1');

-- Remove Halloween Content from Blighted Isle
DELETE FROM `war_world`.`gameobject_spawns` WHERE (`Guid` = '2076380');
DELETE FROM `war_world`.`gameobject_spawns` WHERE (`Guid` = '2076383');
DELETE FROM `war_world`.`gameobject_spawns` WHERE (`Guid` = '2076385');
DELETE FROM `war_world`.`gameobject_spawns` WHERE (`Guid` = '2076389');
DELETE FROM `war_world`.`creature_spawns` WHERE (`Guid` = '1185486');


-- Remove Token of Dead Drops & Loot Groups
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd72ba0db-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd73104e9-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd73664db-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd73b856a-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7409cb6-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd745d3df-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd74bcbbc-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7513aeb-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd75900c9-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd75ed510-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd76519a7-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd76afe79-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7704e72-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7775d81-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd77d1b92-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7824462-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd787728a-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd78dba5e-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7931821-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7984344-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd79d699e-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7a2bbf5-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7a83916-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7aeb8af-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7b3ec79-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7b94ae7-a855-11e7-8dcf-000c29d63948');
DELETE FROM `war_world`.`loot_group_items` WHERE (`Loot_Group_Items_ID` = 'd7bf78e9-a855-11e7-8dcf-000c29d63948');
--
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '545');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '546');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '547');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '548');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '549');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '550');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '551');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '552');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '553');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '554');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '555');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '556');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '557');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '558');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '559');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '560');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '561');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '562');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '563');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '564');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '565');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '566');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '567');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '568');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '569');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '570');
DELETE FROM `war_world`.`loot_groups` WHERE (`Entry` = '571');

-- Delete Torque Stuff
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28995') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28995') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28995') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28995') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28994') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28994') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28994') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28994') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28993') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28993') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28993') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28993') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28992') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28992') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28992') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28992') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28991') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28991') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28991') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28991') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28990') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28990') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28990') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28990') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28989') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28989') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28989') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28989') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28988') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28988') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28988') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28988') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28987') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28987') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28987') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28987') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28986') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28986') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28986') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28986') and (`CommandID` = '2') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28985') and (`CommandID` = '0') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28985') and (`CommandID` = '0') and (`CommandSequence` = '1');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28985') and (`CommandID` = '1') and (`CommandSequence` = '0');
DELETE FROM `war_world`.`buff_commands` WHERE (`Entry` = '28985') and (`CommandID` = '2') and (`CommandSequence` = '0');
